name: Deploy Portfolio

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and Theme
        run: |
          pip install mkdocs mkdocs-material mkdocs-minify-plugin

      - name: Build MkDocs Site
        run: mkdocs build

      - name: Install cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Setup SSH Key and Config
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat >> ~/.ssh/config <<END
          Host ssh.damienfoster.net
            ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h --service-token-id ${{ secrets.CF_CLIENT_ID }} --service-token-secret ${{ secrets.CF_CLIENT_SECRET }}
            StrictHostKeyChecking no
          END

      - name: Deploy Site to Lenovo
        run: |
          # 1. Connect and delete old files first to ensure a clean slate
          ssh -i ~/.ssh/id_ed25519 d4mien@ssh.damienfoster.net "rm -rf /home/d4mien/nginx/html/*"

          # 2. Transfer the new MkDocs site content
          scp -v -r -i ~/.ssh/id_ed25519 ./site/* d4mien@ssh.damienfoster.net:/home/d4mien/nginx/html/
