name: Barebones Test Deploy

on:
  push:
    branches:
      - master

jobs:
  test-connectivity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # This step "opens the door" through Cloudflare Zero Trust
      - name: install cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Test SSH Connection via Cloudflare
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          # This line tells SSH to use the Cloudflare tunnel
          proxy_command: /usr/local/bin/cloudflared access ssh --id ${{ secrets.CF_CLIENT_ID }} --secret ${{ secrets.CF_CLIENT_SECRET }} --target ${{ secrets.SSH_HOST }}
          source: "index.html"
          target: "/var/www/html"
          strip_components: 0
